name: CI Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        run: |
          ./gradlew assemble --no-daemon
          ./gradlew --stop

      - name: Build Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          docker build -t food-delivery .
          docker tag food-delivery:latest hyuuny/food-delivery:latest
          docker push hyuuny/food-delivery:latest

      - name: Run Tests
        run: |
          ./gradlew test --no-daemon
          ./gradlew --stop

      - name: Check Test Results
        run: |
          TEST_EXIT_CODE=$?
          if [ $TEST_EXIT_CODE -ne 0 ]; then
            echo "Tests failed. Exiting with code $TEST_EXIT_CODE"
            exit $TEST_EXIT_CODE
          fi

      - name: Archive Build Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: build/libs/*.jar